// IVMAP — Hand-written seed data for Gujarat CCTV hackathon mock MVP
import type { Camera, VehicleSighting, WatchlistEntity, Alert, DashboardSummary } from '../../types';

// ─── Cameras ──────────────────────────────────────────────────────────────────
export const cameras: Camera[] = [
  {
    id: 'cam-001',
    name: 'Ahmedabad — Ring Road Junction',
    department: 'Traffic Police, Ahmedabad',
    lat: 23.0225,
    lng: 72.5714,
    status: 'online',
    vendor: 'Hikvision',
  },
  {
    id: 'cam-002',
    name: 'Gandhinagar — Sector 11 Roundabout',
    department: 'Gandhinagar Municipal Corp',
    lat: 23.2156,
    lng: 72.6369,
    status: 'online',
    vendor: 'Dahua',
  },
  {
    id: 'cam-003',
    name: 'Surat — Adajan Bridge Toll',
    department: 'NHAI Gujarat',
    lat: 21.1702,
    lng: 72.8311,
    status: 'online',
    vendor: 'Bosch',
  },
  {
    id: 'cam-004',
    name: 'Vadodara — Sayajigunj Crossing',
    department: 'Traffic Police, Vadodara',
    lat: 22.3072,
    lng: 73.1812,
    status: 'online',
    vendor: 'Hikvision',
  },
  {
    id: 'cam-005',
    name: 'Rajkot — Kalavad Road Gate',
    department: 'Traffic Police, Rajkot',
    lat: 22.3039,
    lng: 70.8022,
    status: 'offline',
    vendor: 'CP-Plus',
  },
  {
    id: 'cam-006',
    name: 'Ahmedabad — SG Highway Flyover',
    department: 'Traffic Police, Ahmedabad',
    lat: 23.0469,
    lng: 72.5090,
    status: 'online',
    vendor: 'Hikvision',
  },
  {
    id: 'cam-007',
    name: 'Surat — Udhna Char Rasta',
    department: 'Surat Municipal Corp',
    lat: 21.1985,
    lng: 72.8500,
    status: 'offline',
    vendor: 'Dahua',
  },
  {
    id: 'cam-008',
    name: 'Bhavnagar — NH-48 Entry Gate',
    department: 'NHAI Gujarat',
    lat: 21.7645,
    lng: 72.1519,
    status: 'online',
    vendor: 'Bosch',
  },
];

// ─── Watchlist Entities ───────────────────────────────────────────────────────
export const watchlistEntities: WatchlistEntity[] = [
  {
    id: 'wl-001',
    entityType: 'vehicle',
    category: 'stolen',
    priority: 'critical',
    status: 'active',
    referenceNo: 'GJ/SV/2024/0581',
    description: 'Stolen white Swift Dezire, reported missing from Paldi, Ahmedabad.',
    plateNumber: 'GJ01AB1234',
  },
  {
    id: 'wl-002',
    entityType: 'vehicle',
    category: 'wanted',
    priority: 'high',
    status: 'active',
    referenceNo: 'GJ/WV/2024/1102',
    description: 'Vehicle linked to armed robbery in Surat on 2024-11-15.',
    plateNumber: 'GJ05CD5678',
  },
  {
    id: 'wl-003',
    entityType: 'vehicle',
    category: 'blacklisted',
    priority: 'medium',
    status: 'active',
    referenceNo: 'GJ/BL/2024/0220',
    description: 'Repeat traffic violator, licence suspended.',
    plateNumber: 'GJ06EF9012',
  },
  {
    id: 'wl-004',
    entityType: 'vehicle',
    category: 'suspect',
    priority: 'high',
    status: 'active',
    referenceNo: 'GJ/SUS/2024/0078',
    description: 'Truck seen near drug seizure site in Vapi.',
    plateNumber: 'GJ15GH3456',
  },
  {
    id: 'wl-005',
    entityType: 'vehicle',
    category: 'missing',
    priority: 'medium',
    status: 'active',
    referenceNo: 'GJ/MV/2025/0031',
    description: 'Vehicle belonging to missing person case, Gandhinagar.',
    plateNumber: 'GJ18IJ7890',
  },
  {
    id: 'wl-006',
    entityType: 'vehicle',
    category: 'other',
    priority: 'low',
    status: 'expired',
    referenceNo: 'GJ/OT/2023/9901',
    description: 'Flagged for unpaid toll violations (5+ instances).',
    plateNumber: 'GJ08KL1357',
  },
];

// Helper: timestamp helpers relative to now
const hoursAgo = (h: number) => new Date(Date.now() - h * 3600 * 1000).toISOString();
const minsAgo = (m: number) => new Date(Date.now() - m * 60 * 1000).toISOString();

// ─── Vehicle Sightings ────────────────────────────────────────────────────────
// GJ01AB1234 has 3 sightings across cam-001, cam-006, cam-002 → route demo-able
// GJ05CD5678 has 2 sightings across cam-003, cam-007
export const vehicleSightings: VehicleSighting[] = [
  // GJ01AB1234 — stolen Swift, multi-camera route
  {
    id: 'vs-001',
    vehicleId: 'v-001',
    plateNumber: 'GJ01AB1234',
    cameraId: 'cam-001',
    detectedAt: hoursAgo(18),
    ocrConfidence: 0.97,
    detectionConfidence: 0.94,
    combinedConfidence: 0.96,
    evidenceFrameUrl: '/mock-frames/vs-001.jpg',
    watchlistMatchId: 'wl-001',
  },
  {
    id: 'vs-002',
    vehicleId: 'v-001',
    plateNumber: 'GJ01AB1234',
    cameraId: 'cam-006',
    detectedAt: hoursAgo(14),
    ocrConfidence: 0.91,
    detectionConfidence: 0.89,
    combinedConfidence: 0.90,
    evidenceFrameUrl: '/mock-frames/vs-002.jpg',
    watchlistMatchId: 'wl-001',
  },
  {
    id: 'vs-003',
    vehicleId: 'v-001',
    plateNumber: 'GJ01AB1234',
    cameraId: 'cam-002',
    detectedAt: hoursAgo(6),
    ocrConfidence: 0.98,
    detectionConfidence: 0.96,
    combinedConfidence: 0.97,
    evidenceFrameUrl: '/mock-frames/vs-003.jpg',
    watchlistMatchId: 'wl-001',
  },
  // GJ05CD5678 — wanted vehicle, 2 cameras
  {
    id: 'vs-004',
    vehicleId: 'v-002',
    plateNumber: 'GJ05CD5678',
    cameraId: 'cam-003',
    detectedAt: hoursAgo(20),
    ocrConfidence: 0.88,
    detectionConfidence: 0.85,
    combinedConfidence: 0.87,
    evidenceFrameUrl: '/mock-frames/vs-004.jpg',
    watchlistMatchId: 'wl-002',
  },
  {
    id: 'vs-005',
    vehicleId: 'v-002',
    plateNumber: 'GJ05CD5678',
    cameraId: 'cam-007',
    detectedAt: hoursAgo(8),
    ocrConfidence: 0.82,
    detectionConfidence: 0.80,
    combinedConfidence: 0.81,
    evidenceFrameUrl: '/mock-frames/vs-005.jpg',
    watchlistMatchId: 'wl-002',
  },
  // GJ06EF9012 — blacklisted
  {
    id: 'vs-006',
    vehicleId: 'v-003',
    plateNumber: 'GJ06EF9012',
    cameraId: 'cam-004',
    detectedAt: hoursAgo(22),
    ocrConfidence: 0.93,
    detectionConfidence: 0.90,
    combinedConfidence: 0.92,
    evidenceFrameUrl: '/mock-frames/vs-006.jpg',
    watchlistMatchId: 'wl-003',
  },
  // GJ15GH3456 — suspect truck
  {
    id: 'vs-007',
    vehicleId: 'v-004',
    plateNumber: 'GJ15GH3456',
    cameraId: 'cam-008',
    detectedAt: hoursAgo(12),
    ocrConfidence: 0.86,
    detectionConfidence: 0.83,
    combinedConfidence: 0.85,
    evidenceFrameUrl: '/mock-frames/vs-007.jpg',
    watchlistMatchId: 'wl-004',
  },
  {
    id: 'vs-008',
    vehicleId: 'v-004',
    plateNumber: 'GJ15GH3456',
    cameraId: 'cam-001',
    detectedAt: hoursAgo(4),
    ocrConfidence: 0.90,
    detectionConfidence: 0.88,
    combinedConfidence: 0.89,
    evidenceFrameUrl: '/mock-frames/vs-008.jpg',
    watchlistMatchId: 'wl-004',
  },
  // GJ18IJ7890 — missing vehicle
  {
    id: 'vs-009',
    vehicleId: 'v-005',
    plateNumber: 'GJ18IJ7890',
    cameraId: 'cam-002',
    detectedAt: hoursAgo(16),
    ocrConfidence: 0.79,
    detectionConfidence: 0.76,
    combinedConfidence: 0.78,
    evidenceFrameUrl: '/mock-frames/vs-009.jpg',
    watchlistMatchId: 'wl-005',
  },
  // GJ08KL1357 — toll violator (no active match)
  {
    id: 'vs-010',
    vehicleId: 'v-006',
    plateNumber: 'GJ08KL1357',
    cameraId: 'cam-003',
    detectedAt: hoursAgo(10),
    ocrConfidence: 0.95,
    detectionConfidence: 0.93,
    combinedConfidence: 0.94,
    evidenceFrameUrl: '/mock-frames/vs-010.jpg',
  },
  // Non-watchlist plates — daily traffic volume
  {
    id: 'vs-011',
    vehicleId: 'v-007',
    plateNumber: 'GJ02MN2468',
    cameraId: 'cam-001',
    detectedAt: minsAgo(45),
    ocrConfidence: 0.99,
    detectionConfidence: 0.97,
    combinedConfidence: 0.98,
    evidenceFrameUrl: '/mock-frames/vs-011.jpg',
  },
  {
    id: 'vs-012',
    vehicleId: 'v-008',
    plateNumber: 'GJ03OP1357',
    cameraId: 'cam-006',
    detectedAt: minsAgo(30),
    ocrConfidence: 0.96,
    detectionConfidence: 0.94,
    combinedConfidence: 0.95,
    evidenceFrameUrl: '/mock-frames/vs-012.jpg',
  },
  {
    id: 'vs-013',
    vehicleId: 'v-009',
    plateNumber: 'GJ04QR9753',
    cameraId: 'cam-004',
    detectedAt: minsAgo(15),
    ocrConfidence: 0.88,
    detectionConfidence: 0.86,
    combinedConfidence: 0.87,
    evidenceFrameUrl: '/mock-frames/vs-013.jpg',
  },
  {
    id: 'vs-014',
    vehicleId: 'v-010',
    plateNumber: 'GJ09ST2580',
    cameraId: 'cam-008',
    detectedAt: minsAgo(8),
    ocrConfidence: 0.92,
    detectionConfidence: 0.90,
    combinedConfidence: 0.91,
    evidenceFrameUrl: '/mock-frames/vs-014.jpg',
  },
  {
    id: 'vs-015',
    vehicleId: 'v-011',
    plateNumber: 'GJ11UV3691',
    cameraId: 'cam-002',
    detectedAt: minsAgo(3),
    ocrConfidence: 0.85,
    detectionConfidence: 0.83,
    combinedConfidence: 0.84,
    evidenceFrameUrl: '/mock-frames/vs-015.jpg',
  },
];

// ─── Alerts ───────────────────────────────────────────────────────────────────
export const alerts: Alert[] = [
  {
    id: 'al-001',
    watchlistId: 'wl-001',
    vehicleSightingId: 'vs-001',
    priority: 'critical',
    status: 'new',
    createdAt: hoursAgo(18),
    cameraName: 'Ahmedabad — Ring Road Junction',
    plateNumber: 'GJ01AB1234',
    category: 'stolen',
  },
  {
    id: 'al-002',
    watchlistId: 'wl-001',
    vehicleSightingId: 'vs-002',
    priority: 'critical',
    status: 'acknowledged',
    createdAt: hoursAgo(14),
    cameraName: 'Ahmedabad — SG Highway Flyover',
    plateNumber: 'GJ01AB1234',
    category: 'stolen',
  },
  {
    id: 'al-003',
    watchlistId: 'wl-001',
    vehicleSightingId: 'vs-003',
    priority: 'critical',
    status: 'new',
    createdAt: hoursAgo(6),
    cameraName: 'Gandhinagar — Sector 11 Roundabout',
    plateNumber: 'GJ01AB1234',
    category: 'stolen',
  },
  {
    id: 'al-004',
    watchlistId: 'wl-002',
    vehicleSightingId: 'vs-004',
    priority: 'high',
    status: 'acknowledged',
    createdAt: hoursAgo(20),
    cameraName: 'Surat — Adajan Bridge Toll',
    plateNumber: 'GJ05CD5678',
    category: 'wanted',
  },
  {
    id: 'al-005',
    watchlistId: 'wl-002',
    vehicleSightingId: 'vs-005',
    priority: 'high',
    status: 'new',
    createdAt: hoursAgo(8),
    cameraName: 'Surat — Udhna Char Rasta',
    plateNumber: 'GJ05CD5678',
    category: 'wanted',
  },
  {
    id: 'al-006',
    watchlistId: 'wl-003',
    vehicleSightingId: 'vs-006',
    priority: 'medium',
    status: 'resolved',
    createdAt: hoursAgo(22),
    cameraName: 'Vadodara — Sayajigunj Crossing',
    plateNumber: 'GJ06EF9012',
    category: 'blacklisted',
  },
  {
    id: 'al-007',
    watchlistId: 'wl-004',
    vehicleSightingId: 'vs-007',
    priority: 'high',
    status: 'new',
    createdAt: hoursAgo(12),
    cameraName: 'Bhavnagar — NH-48 Entry Gate',
    plateNumber: 'GJ15GH3456',
    category: 'suspect',
  },
  {
    id: 'al-008',
    watchlistId: 'wl-005',
    vehicleSightingId: 'vs-009',
    priority: 'medium',
    status: 'new',
    createdAt: hoursAgo(16),
    cameraName: 'Gandhinagar — Sector 11 Roundabout',
    plateNumber: 'GJ18IJ7890',
    category: 'missing',
  },
];

// ─── Dashboard Summary (derived, not hardcoded against contradictory numbers) ──
const camerasOnline = cameras.filter((c) => c.status === 'online').length;
const camerasOffline = cameras.filter((c) => c.status === 'offline').length;
const activeAlerts = alerts.filter((a) => a.status !== 'resolved').length;
const criticalIncidents = alerts.filter(
  (a) => a.priority === 'critical' && a.status !== 'resolved',
).length;

// Vehicles tracked "today" = unique plates seen in the last 24h (all our sightings are within 24h)
const uniquePlates = new Set(vehicleSightings.map((vs) => vs.plateNumber));

export const dashboardSummary: DashboardSummary = {
  totalCameras: cameras.length,
  camerasOnline,
  camerasOffline,
  activeAlerts,
  vehiclesTrackedToday: uniquePlates.size,
  criticalIncidents,
  systemHealth: camerasOffline > cameras.length * 0.3 ? 'degraded' : 'healthy',
};
